esitmation_buffer: 0.2
storage_buffer: 0.1
storage_display_unit: GB

vm_os_storage_gb: 70
vm_os_storage_group: 'SAS'

usage:
  users:
    model: 'date_range_value'
    ranges:
      - ['20170601', '20170801', 45000]
      - ['20170901', '20220801', 100000]
  forms:
    model: 'derived_factor'
    start_with: 27039499
    dependant_field: 'users'
    factor: 600
  forms_total:
    model: 'cumulative'
    dependant_field: 'forms'
  cases:
    start_with: 54550221
    model: 'derived_factor'
    dependant_field: 'users'
    factor: 200
  cases_total:
    model: 'cumulative'
    dependant_field: 'cases'
  case_transactions:
    start_with: 102979228
    model: 'derived_factor'
    dependant_field: 'users'
    factor: 1600
  case_transactions_total:
    model: 'cumulative'
    dependant_field: 'case_transactions'
  task_cases:
    start_with: 4278351
    model: 'derived_factor'
    dependant_field: 'users'
    factor: 100
  task_cases_total:
    model: 'cumulative_limited_lifespan'
    dependant_field: 'task_cases'
    lifespan: 1
  person_cases:
    model: 'derived_factor'
    dependant_field: 'users'
    factor: 1600
  phone_numbers:
    model: 'derived_factor'
    dependant_field: 'person_cases'
    factor: 1
  task_ledgers:
    start_with: 13233156
    model: 'derived_factor'
    dependant_field: 'task_cases'
    factor: 5
  task_ledger_updates:
    model: 'derived_factor'
    dependant_field: 'task_cases'
    factor: 4
  synclogs:
    model: 'derived_factor'
    dependant_field: 'users'
    factor: 10
  device_logs:
    model: 'derived_factor'
    dependant_field: 'users'
    factor: 1600
  device_logs_total:
    model: 'cumulative_limited_lifespan'
    dependant_field: 'device_logs'
    lifespan: 1
  images:
    model: 'derived_factor'
    dependant_field: 'users'
    factor: 32.5
  images_total:
    model: 'cumulative_limited_lifespan'
    dependant_field: 'images'
    lifespan: 3
  case_indices:
    model: 'derived_factor'
    dependant_field: 'cases_total'
    factor: 0.92
  kafak_changes:
    model: 'derived_sum'
    dependant_fields: ['forms', 'cases', 'case_transactions', 'task_ledger_updates']  # sms

storage:
  sql_primary:
    group: 'SSD'
    static_redundancy_factor: 2
    data_models:  
      - referenced_field: 'forms_total'
        unit_bytes: 1200
      - referenced_field: 'cases_total'
        unit_bytes: 1800
      - referenced_field: 'case_indices'
        unit_bytes: 380
      - referenced_field: 'case_transactions_total'
        unit_bytes: 515
      - referenced_field: 'task_ledgers'
        unit_bytes: 450
      - referenced_field: 'task_ledger_updates'
        unit_bytes: 420
      - referenced_field: 'images_total'
        unit_bytes: 370
  sql_meta:
    group: 'SSD'
    static_redundancy_factor: 2
    data_models:
      - referenced_field: 'phone_numbers'
        unit_bytes: 660
      - referenced_field: 'device_logs_total'
        unit_bytes: 1200
#      - referenced_field: 'sms'
#        unit_bytes: ?
  couchdb_synclogs:
    group: 'SSD'
    static_redundancy_factor: 3
    data_models:
      - referenced_field: 'synclogs'
        unit_bytes: 210000
  elastic:
    group: 'SAS'
    static_redundancy_factor: 2
    data_models:
      - referenced_field: 'forms_total'
        unit_bytes: 5500
      - referenced_field: 'cases_total'
        unit_bytes: 1800
      - referenced_field: 'case_transactions_total'
        unit_bytes: 250
  kafka:
    group: 'SAS'
    static_redundancy_factor: 1
    data_models:
      - referenced_field: 'kafak_changes'
        unit_bytes: 500
  riak:
    group: 'SAS'
    static_redundancy_factor: 3
    data_models:
      - referenced_field: 'forms_total'
        unit_bytes: 11000
      - referenced_field: 'images_total'
        unit_bytes: 50000
  ucr:
    # This is a rough estimate.
    # The person case UCR is 35% of total UCR usage.
    group: 'SSD'
    dynamic_redundancy_factor:
      referenced_field: 'users'
      factor: 0.00002
    data_models:
      - referenced_field: 'person_cases'
        unit_bytes: 10000  # inflated to account for others UCRs
#  warehouse:  # TODO
compute:
  pillowtop:
    cores_per_vm: 4
    ram_per_vm: 6
    cores_per_process: 0.5
    ram_per_process: 0.7
    processes:
      - name: 'static-cases'
        capacity: 1875
      - name: 'case-to-es'
        capacity: 5625
      - name: 'ucr-static-forms'
        capacity: 5625
      - name: 'forms-to-es'
        capacity: 11250
      - name: 'other'
        capacity: 11250
      - name: 'Kafka-ucr-static-person_cases'
        capacity: 5625
  celery:
    cores_per_vm: 6
    ram_per_vm: 6
    cores_per_process: 1
    ram_per_process: 0.5
    processes:
      - name: 'other'
        capacity: 60000
      - name: 'reminder_case_update_queue'
        capacity: 15000
      - name: 'reminder_queue'
        capacity: 19500
      - name: 'reminder_rule_queue'
        capacity: 100000
      - name: 'sms_queue'
        capacity: 30000
      - name: 'async_restore_queue'
        capacity: 4500
  django:
    cores_per_vm: 8
    ram_per_vm: 16
    processes:
      - capacity: 5000
  pg_shards:
    cores_per_vm: 16
    ram_per_vm: 48
    processes:
      - capacity: 10000
  pg_ucr:
    cores_per_vm: 16
    ram_per_vm: 48
    processes:
      - capacity: 25000
  pg_auth_meta:
    cores_per_vm: 16
    ram_per_vm: 48
    processes:
      - capacity: 25000
  elastic:
    cores_per_vm: 8
    ram_per_vm: 48
    processes:
      - capacity: 17500
  redis:
    cores_per_vm: 4
    ram_per_vm: 16
    processes:
      - capacity: 50000
  nginx:
    cores_per_vm: 4
    ram_per_vm: 2
    processes:
      - capacity: 25000
  couch:
    cores_per_vm: 8
    ram_per_vm: 32
    processes:
      - capacity: 40000
  rabbitmq:
    cores_per_vm: 6
    ram_per_vm: 16
    processes:
      - capacity: 100000
  kafka:
    cores_per_vm: 8
    ram_per_vm: 16
    processes:
      - capacity: 50000
  formplayer:
    cores_per_vm: 8
    ram_per_vm: 16
    processes:
      - capacity: 50000
  riak:
    cores_per_vm: 6
    ram_per_vm: 16
    processes:
      - capacity: 12500
