estimation_buffer: 0.2
storage_buffer: 0.1
storage_display_unit: GB

vm_os_storage_gb: 70
vm_os_storage_group: 'SAS'

usage:
  users:
    model: 'date_range_value'
    ranges:
      - ['20170601', 1000000]
      - ['20170701', 2000000]
      - ['20170801', 3000000]
  forms:
    model: 'derived_factor'
    start_with: 5000000
    dependant_field: 'users'
    factor: 1000000
